const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],DAY=86400000;
const iso=d=>{let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`},today=()=>iso(new Date());
const EM={sport:"🏃",maison:"🧹",sante:"❤️",perso:"🌱"};
const SHARKS=[
["Requin gris","Carcharhinus plumbeus","Commun",0,"🦈","Départ"],["Requin pointe noire","Carcharhinus melanopterus","Commun",350,"🦈","Boutique"],["Requin pointe blanche","Triaenodon obesus","Commun",450,"🦈","Boutique"],["Requin bleu","Prionace glauca","Commun",600,"🦈","Boutique"],["Requin nourrice","Ginglymostoma cirratum","Commun",700,"🦈","Boutique"],["Requin citron","Negaprion brevirostris","Commun",800,"🦈","Boutique"],["Requin corail","Carcharhinus amblyrhynchos","Commun",900,"🦈","Boutique"],["Requin zèbre","Stegostoma tigrinum","Rare",1400,"🦈","10 activités"],["Requin-renard","Alopias vulpinus","Rare",1800,"🦈","25 activités"],["Requin mako","Isurus oxyrinchus","Rare",2200,"🦈","Niveau 10"],["Requin bouledogue","Carcharhinus leucas","Rare",2600,"🦈","Boutique"],["Requin marteau","Sphyrna lewini","Rare",3000,"🔨","10 objectifs atteints"],["Requin-tapis","Orectolobus maculatus","Rare",3200,"🦈","Boutique"],["Requin-scie","Pristiophorus cirratus","Rare",3400,"🪚","Boutique"],["Requin-lutin","Mitsukurina owstoni","Épique",5000,"👺","50 activités"],["Requin-lézard","Chlamydoselachus anguineus","Épique",5500,"🐉","Boutique"],["Requin tigre","Galeocerdo cuvier","Épique",6000,"🐯","Niveau 20"],["Requin du Groenland","Somniosus microcephalus","Épique",6500,"🦈","100 activités"],["Requin griset","Hexanchus griseus","Épique",7000,"🦈","Boutique"],["Requin ange","Squatina squatina","Épique",7200,"🪽","Boutique"],["Grand marteau","Sphyrna mokarran","Légendaire",10000,"🔨","Niveau 30"],["Grand requin blanc","Carcharodon carcharias","Légendaire",12000,"🦈","Niveau 40"],["Requin pèlerin","Cetorhinus maximus","Légendaire",14000,"🦈","200 activités"],["Requin-baleine","Rhincodon typus","Légendaire",16000,"🐋","Niveau 50"],["Mégalodon","Otodus megalodon","Mythique",25000,"🦈","Collection ultime"]];
const DECOR=[
["algue","Petite algue","plante","Commun",30,"🌿"],["herbe","Herbes marines","plante","Commun",40,"🌱"],["kelp","Grande algue","plante","Rare",180,"🎋"],["rocher","Petit rocher","rocher","Commun",50,"🪨"],["rocher2","Rocher volcanique","rocher","Rare",220,"🗿"],["corail","Corail rouge","corail","Commun",80,"🪸"],["corail2","Corail cerveau","corail","Rare",250,"🧠"],["coquillage","Coquillage","special","Commun",40,"🐚"],["amphore","Amphore","special","Rare",350,"🏺"],["poissons","Banc de poissons","animal","Rare",400,"🐠"],["crabe","Petit crabe","animal","Rare",450,"🦀"],["meduse","Méduse lumineuse","animal","Épique",900,"🪼"],["ancre","Ancre","special","Rare",600,"⚓"],["coffre","Coffre au trésor","special","Épique",1500,"🧰"],["epave","Épave","special","Épique",1800,"🚢"],["statue","Statue engloutie","special","Légendaire",3000,"🗿"],["cristal","Cristal abyssal","special","Légendaire",4500,"💎"]];
const DEST=[["Récif corallien","🪸",250],["Pleine mer","🌊",500],["Mer tropicale","🏝️",800],["Océan arctique","❄️",1200],["Abysses","🌌",1800],["Fosse océanique","🕳️",2500]];
const starterInventory=()=>({algue:3,herbe:2,rocher:2,corail:2,coquillage:2});
const starterPlaced=()=>[
{id:"p1",decor:"algue",x:15,y:83},{id:"p2",decor:"algue",x:27,y:87},{id:"p3",decor:"rocher",x:48,y:88},{id:"p4",decor:"corail",x:72,y:84},{id:"p5",decor:"coquillage",x:84,y:90}
];
const blank=()=>({version:4,xp:0,teeth:100,goals:[],activities:[],owned:["Requin gris"],activeShark:"Requin gris",aquariumSharks:["Requin gris"],affinity:{"Requin gris":0},expedition:null,completedExpeditions:0,inventory:starterInventory(),placedDecor:starterPlaced(),oceanTutorialSeen:false});
let data=JSON.parse(localStorage.getItem("sharkHabitsV4")||"null")||blank(),weekOffset=0,goalFilter="all",rarityFilter="all",decorFilter="all",selectedDecor=null,selectedPlaced=null,placementHistory=[];
function normalize(){data.inventory=data.inventory||starterInventory();data.placedDecor=data.placedDecor||starterPlaced();data.aquariumSharks=data.aquariumSharks||[data.activeShark||"Requin gris"];data.affinity=data.affinity||{"Requin gris":0};data.completedExpeditions=data.completedExpeditions||0}
normalize();
function save(){localStorage.setItem("sharkHabitsV4",JSON.stringify(data))}
function monday(d=new Date()){d=new Date(d);let n=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d}
function bounds(g,date=new Date()){let d=new Date(date),s,e;if(g.repeat==="day"){s=new Date(d);s.setHours(0,0,0,0);e=new Date(s.getTime()+DAY)}else if(g.repeat==="month"){s=new Date(d.getFullYear(),d.getMonth(),1);e=new Date(d.getFullYear(),d.getMonth()+1,1)}else{s=monday(d);e=new Date(s.getTime()+7*DAY)}return[s,e]}
function actsFor(g){return data.activities.filter(a=>a.goal===g.id)}
function valueFor(g,date=new Date()){let a=actsFor(g);if(g.type==="metric"){a=a.sort((x,y)=>x.date.localeCompare(y.date));return a.length?a[a.length-1].value:(g.baseline||0)}if(["long","once"].includes(g.type))return a.reduce((s,x)=>s+x.value,0);let[s,e]=bounds(g,date);return a.filter(x=>{let d=new Date(x.date+"T12:00");return d>=s&&d<e}).reduce((s,x)=>s+x.value,0)}
function pct(g,v=valueFor(g)){if(g.type==="metric"){let total=Math.abs((g.baseline||v)-g.target),done=Math.abs((g.baseline||v)-v);return Math.max(0,Math.min(100,total?done/total*100:100))}return Math.min(100,g.target?v/g.target*100:0)}
function achievedCount(){return data.goals.filter(g=>pct(g)>=100).length}
function level(){return Math.floor(data.xp/250)+1}
function unlocked(s){let[n,latin,r,c,e,how]=s,a=data.activities.length,ac=achievedCount(),lvl=level();return data.owned.includes(n)||how==="Départ"||(how==="10 activités"&&a>=10)||(how==="25 activités"&&a>=25)||(how==="50 activités"&&a>=50)||(how==="100 activités"&&a>=100)||(how==="200 activités"&&a>=200)||(how==="Niveau 10"&&lvl>=10)||(how==="Niveau 20"&&lvl>=20)||(how==="Niveau 30"&&lvl>=30)||(how==="Niveau 40"&&lvl>=40)||(how==="Niveau 50"&&lvl>=50)||(how==="10 objectifs atteints"&&ac>=10)}
function syncUnlocks(){SHARKS.forEach(s=>{if(unlocked(s)&&!data.owned.includes(s[0])&&s[5]!=="Boutique"&&s[5]!=="Collection ultime")data.owned.push(s[0])})}
function decorById(id){return DECOR.find(d=>d[0]===id)}
function usedCount(id){return data.placedDecor.filter(p=>p.decor===id).length}
function availableCount(id){return Math.max(0,(data.inventory[id]||0)-usedCount(id))}
function oceanLevel(){let unique=Object.keys(data.inventory).filter(k=>data.inventory[k]>0).length;return Math.max(1,Math.floor((unique+data.owned.length+(data.completedExpeditions||0))/4))}
function empty(msg,icon="🌊"){return `<div class="card empty"><div class="big">${icon}</div><b>${msg}</b></div>`}
function goalCard(g,date=new Date()){let v=valueFor(g,date),p=pct(g,v),rep=g.repeat==="week"?"Cette semaine":g.repeat==="month"?"Ce mois":g.repeat==="day"?"Aujourd'hui":g.type==="metric"?"Mesure":g.type==="long"?"Long terme":"Ponctuel";return `<div class="goalcard"><div class="goalTop"><span class="emoji">${EM[g.category]||"🎯"}</span><div class="goalName">${g.name}<div class="muted">${rep}</div></div><button class="mini addAct" data-id="${g.id}">＋</button></div><div class="progressrow"><span>${+v.toFixed(1)} ${g.unit||""} ${g.type==="metric"?"→ "+g.target+" "+(g.unit||""):"/ "+g.target+" "+(g.unit||"")}</span><b>${Math.round(p)}%</b></div><div class="progress"><i style="width:${p}%"></i></div><div class="rowbuttons"><button class="textbtn editGoal" data-id="${g.id}">Modifier</button><button class="textbtn archiveGoal" data-id="${g.id}">${g.archived?"Réactiver":"Archiver"}</button><button class="danger deleteGoal" data-id="${g.id}">Supprimer</button></div></div>`}
function render(){
 syncUnlocks();save();let lvl=level(),rem=data.xp%250;$("#level").textContent="Niveau "+lvl;$("#xpText").textContent=`${rem} / 250 XP`;$("#xpBar").style.width=rem/250*100+"%";$("#teeth").textContent=data.teeth;$("#shopTeeth").textContent=data.teeth;
 let shark=SHARKS.find(s=>s[0]===data.activeShark)||SHARKS[0];$("#heroShark").textContent=shark[4];$("#todayLabel").textContent=new Date().toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long"});
 renderMiniDecor();
 let active=data.goals.filter(g=>!g.archived);$("#emptyWelcome").innerHTML=!active.length?`<div class="card empty"><div class="big">🦈</div><h2>Ton océan est prêt</h2><p class="muted">Aucun objectif n'est imposé. Ton kit de décoration de départ t'attend déjà dans l'aquarium.</p><button class="primary createFirst">＋ Créer mon premier objectif</button></div>`:"";
 $("#todayList").innerHTML=active.filter(g=>["habit","period"].includes(g.type)).map(goalCard).join("")||empty("Aucune habitude active aujourd'hui","☀️");
 $("#currentGoals").innerHTML=active.filter(g=>["long","metric","once"].includes(g.type)).map(goalCard).join("")||empty("Aucun objectif long terme","🎯");
 $("#goalList").innerHTML=active.filter(g=>goalFilter==="all"||g.category===goalFilter).map(goalCard).join("")||empty("Aucun objectif dans cette catégorie","🎯");
 $("#archivedList").innerHTML=data.goals.filter(g=>g.archived).map(goalCard).join("")||'<p class="muted">Aucun objectif archivé.</p>';
 renderWeek();renderStats();renderDex();renderDecorShop();renderExpedition();renderAquarium();bindDynamic();populateActivity()
}
function renderMiniDecor(){let items=data.placedDecor.slice(0,8);$("#miniDecor").innerHTML=items.map(p=>{let d=decorById(p.decor);return d?`<span class="miniItem" style="left:${p.x}%;bottom:${Math.max(0,95-p.y)}%">${d[5]}</span>`:""}).join("")}
function renderWeek(){let s=monday(new Date(Date.now()+weekOffset*7*DAY)),e=new Date(s.getTime()+6*DAY);$("#weekTitle").textContent=`${s.toLocaleDateString("fr-FR",{day:"numeric",month:"short"})} – ${e.toLocaleDateString("fr-FR",{day:"numeric",month:"short",year:"numeric"})}`;$("#weekGrid").innerHTML=[0,1,2,3,4,5,6].map(i=>{let d=new Date(s.getTime()+i*DAY),ds=iso(d),a=data.activities.filter(x=>x.date===ds);return `<div class="day ${ds===today()?"today":""}"><b>${["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"][i]}</b><div class="num">${d.getDate()}</div><div class="dots">${a.slice(0,4).map(x=>EM[(data.goals.find(g=>g.id===x.goal)||{}).category]||"•").join(" ")}</div></div>`}).join("");let gs=data.goals.filter(g=>!g.archived&&g.repeat==="week");$("#weekGoals").innerHTML=gs.map(g=>goalCard(g,s)).join("")||empty("Aucun objectif hebdomadaire","📅")}
function draw(canvas,A,B=[]){let c=canvas,ctx=c.getContext("2d"),w=c.width,h=c.height,p=36;ctx.clearRect(0,0,w,h);let vals=[...A,...B].filter(Number.isFinite);if(!vals.length)return;let mn=Math.min(...vals),mx=Math.max(...vals);if(mn===mx){mn-=1;mx+=1}let pt=(v,i,n)=>[p+i*(w-2*p)/Math.max(1,n-1),h-p-(v-mn)*(h-2*p)/(mx-mn)];ctx.strokeStyle="#dfe8ea";ctx.lineWidth=1;for(let i=0;i<5;i++){let y=p+i*(h-2*p)/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}[B,A].forEach((arr,j)=>{if(!arr.length)return;ctx.strokeStyle=j?"#0b7189":"#9aa8ac";ctx.lineWidth=j?4:2;ctx.setLineDash(j?[]:[8,6]);ctx.beginPath();arr.forEach((v,i)=>{let[x,y]=pt(v,i,arr.length);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()});ctx.setLineDash([])}
function renderStats(){let weeks=[];for(let k=7;k>=0;k--){let d=new Date(Date.now()-k*7*DAY),gs=data.goals.filter(g=>!g.archived&&g.repeat==="week");weeks.push(gs.length?gs.reduce((s,g)=>s+pct(g,valueFor(g,d)),0)/gs.length:0)}draw($("#weeklyChart"),weeks,[100,100,100,100,100,100,100,100]);let gs=data.goals.filter(g=>!g.archived);$("#analysisSelect").innerHTML=gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join("");let g=gs[0];if(g){let acts=actsFor(g).sort((a,b)=>a.date.localeCompare(b.date)),real=g.type==="metric"?[g.baseline||0,...acts.map(a=>a.value)]:acts.map((a,i)=>acts.slice(0,i+1).reduce((s,x)=>s+x.value,0));if(!real.length)real=[0];let target=real.map((_,i)=>g.type==="metric"?(g.baseline||0)+(g.target-(g.baseline||0))*i/Math.max(1,real.length-1):g.target*i/Math.max(1,real.length-1));draw($("#analysisChart"),real,target);$("#analysisInsight").textContent=`${g.name} : ${+valueFor(g).toFixed(1)} ${g.unit||""}. Cible : ${g.target} ${g.unit||""}. Ligne pointillée = trajectoire cible.`}else{$("#analysisInsight").textContent="Crée un objectif pour afficher son analyse.";draw($("#analysisChart"),[])}$("#statsSummary").innerHTML=`<div class="stat"><span class="muted">Activités</span><b>${data.activities.length}</b></div><div class="stat"><span class="muted">Objectifs atteints</span><b>${achievedCount()}</b></div><div class="stat"><span class="muted">Niveau océan</span><b>${oceanLevel()}</b></div><div class="stat"><span class="muted">Expéditions</span><b>${data.completedExpeditions}</b></div>`}
function renderDex(){let owned=SHARKS.filter(s=>data.owned.includes(s[0])).length;$("#dexCount").textContent=`${owned} / ${SHARKS.length}`;let active=SHARKS.find(s=>s[0]===data.activeShark)||SHARKS[0];$("#activeEmoji").textContent=active[4];$("#activeShark").textContent=active[0];$("#affinity").textContent=`Affinité : ${data.affinity[active[0]]||0} XP`;$("#sharkGrid").innerHTML=SHARKS.filter(s=>rarityFilter==="all"||s[2]===rarityFilter).map(s=>{let[n,latin,r,c,e,how]=s,own=data.owned.includes(n),can=unlocked(s),buy=how==="Boutique";return `<div class="shopitem"><div class="fish">${e}</div>${!own?'<span class="lockBadge">🔒</span>':""}<div class="rarity">${r}</div><b>${n}</b><p class="muted">${latin}</p><p class="muted">${own?"Débloqué":how+(buy?` · ${c} 🦷`:"")}</p>${own?`<button class="primary small chooseShark" data-name="${n}">${data.activeShark===n?"Actif":"Choisir"}</button>`:buy?`<button class="primary small buyShark" data-name="${n}" data-cost="${c}">Acheter</button>`:can?`<button class="primary small claimShark" data-name="${n}">Débloquer</button>`:""}</div>`}).join("");let ach=[["Première nage",data.activities.length>=1],["10 activités",data.activities.length>=10],["100 activités",data.activities.length>=100],["Premier objectif",achievedCount()>=1],["Collectionneur",owned>=10],["Décorateur",data.placedDecor.length>=10],["Explorateur",data.completedExpeditions>=1]];$("#achievements").innerHTML=ach.map(([n,ok])=>`<div class="goalcard achievement"><span>${ok?"🏆":"🔒"}</span><b>${n}</b></div>`).join("")}
function renderDecorShop(){$("#decorShop").innerHTML=DECOR.filter(d=>decorFilter==="all"||d[2]===decorFilter).map(d=>{let[id,n,k,r,c,e]=d,q=data.inventory[id]||0;return `<div class="shopitem"><div class="fish">${e}</div><div class="rarity">${r}</div><b>${n}</b><p class="ownedCount">Possédé : ${q}</p><p><b>${c} 🦷</b></p><button class="primary small buyDecor" data-id="${id}" data-cost="${c}">Acheter</button></div>`}).join("")}
function renderExpedition(){let ex=data.expedition;if(ex){let dest=DEST[ex.dest],p=Math.min(100,ex.progress/dest[2]*100);$("#expeditionBox").innerHTML=`<div class="card expedition"><h2>${dest[1]} ${dest[0]}</h2><p>Ton requin explore cette zone grâce à tes activités.</p><div class="progress"><i style="width:${p}%"></i></div><p>${ex.progress} / ${dest[2]} XP</p>${p>=100?'<button class="primary wide finishExp">Récupérer la récompense</button>':""}</div>`}else $("#expeditionBox").innerHTML=empty("Choisis une destination. Chaque activité fera avancer ton requin.","🧭");$("#destinations").innerHTML=DEST.map((d,i)=>`<div class="goalcard destination"><div class="place">${d[1]}</div><div class="goalName">${d[0]}<div class="muted">${d[2]} XP nécessaires</div></div><button class="primary small startExp" data-i="${i}" ${ex?"disabled":""}>Partir</button></div>`).join("")}
function renderAquarium(){let sharks=(data.aquariumSharks||[data.activeShark]).filter(n=>data.owned.includes(n)).slice(0,Math.min(5,1+Math.floor(oceanLevel()/4)));if(!sharks.includes(data.activeShark))sharks.unshift(data.activeShark);$("#swimmingSharks").innerHTML=sharks.slice(0,5).map((n,i)=>{let s=SHARKS.find(x=>x[0]===n)||SHARKS[0];return `<div class="swimShark" style="left:${12+i*17}%;top:${20+(i%3)*18}%">${s[4]}</div>`}).join("");$("#placedDecor").innerHTML=data.placedDecor.map(p=>{let d=decorById(p.decor);return d?`<button class="placedItem ${selectedPlaced===p.id?"selectedPlaced":""}" data-pid="${p.id}" style="left:${p.x}%;top:${p.y}%" aria-label="${d[1]}">${d[5]}</button>`:""}).join("");$("#oceanLevel").textContent=`Océan niveau ${oceanLevel()} · ${data.placedDecor.length} décorations`;renderInventory()}
function renderInventory(){$("#inventoryStrip").innerHTML=DECOR.filter(d=>(data.inventory[d[0]]||0)>0).map(d=>{let av=availableCount(d[0]);return `<button class="inventoryItem ${selectedDecor===d[0]?"selected":""}" data-decor="${d[0]}" ${av<=0?"disabled":""}><span class="invEmoji">${d[5]}</span><small>${d[1]}</small><b>${av} dispo.</b></button>`}).join("")||'<span class="muted">Ton inventaire est vide.</span>'}
function populateActivity(){let gs=data.goals.filter(g=>!g.archived);$("#activityGoal").innerHTML=gs.map(g=>`<option value="${g.id}">${EM[g.category]||"🎯"} ${g.name}</option>`).join("")}
function bindDynamic(){
 $$(".createFirst").forEach(b=>b.onclick=()=>openGoal());$$(".addAct").forEach(b=>b.onclick=()=>openActivity(b.dataset.id));$$(".editGoal").forEach(b=>b.onclick=()=>openGoal(b.dataset.id));$$(".archiveGoal").forEach(b=>b.onclick=()=>{let g=data.goals.find(x=>x.id===b.dataset.id);g.archived=!g.archived;save();render()});$$(".deleteGoal").forEach(b=>b.onclick=()=>{if(confirm("Supprimer cet objectif et ses activités ?")){data.goals=data.goals.filter(g=>g.id!==b.dataset.id);data.activities=data.activities.filter(a=>a.goal!==b.dataset.id);save();render()}});
 $$(".chooseShark").forEach(b=>b.onclick=()=>{data.activeShark=b.dataset.name;if(!data.aquariumSharks.includes(b.dataset.name))data.aquariumSharks[0]=b.dataset.name;save();render()});
 $$(".buyShark").forEach(b=>b.onclick=()=>{let c=+b.dataset.cost;if(data.teeth<c)return alert("Pas assez de dents.");data.teeth-=c;data.owned.push(b.dataset.name);data.affinity[b.dataset.name]=0;save();render()});
 $$(".claimShark").forEach(b=>b.onclick=()=>{if(!data.owned.includes(b.dataset.name))data.owned.push(b.dataset.name);save();render()});
 $$(".buyDecor").forEach(b=>b.onclick=()=>{let c=+b.dataset.cost;if(data.teeth<c)return alert("Pas assez de dents.");data.teeth-=c;data.inventory[b.dataset.id]=(data.inventory[b.dataset.id]||0)+1;save();render();});
 $$(".startExp").forEach(b=>b.onclick=()=>{data.expedition={dest:+b.dataset.i,progress:0};save();render()});let f=$(".finishExp");if(f)f.onclick=()=>finishExpedition();
 $$(".inventoryItem").forEach(b=>b.onclick=()=>{selectedDecor=b.dataset.decor;selectedPlaced=null;renderAquarium();$("#aquariumHint").textContent="Objet sélectionné : touche l'endroit où tu veux le placer.";});
 $$(".placedItem").forEach(b=>b.onclick=e=>{if(!$("#aquariumScreen").classList.contains("editing"))return;e.stopPropagation();selectedPlaced=b.dataset.pid;selectedDecor=null;renderAquarium();$("#aquariumHint").textContent="Objet sélectionné : touche ailleurs pour le déplacer, ou double-touche pour le ranger.";});
}
function finishExpedition(){let idx=data.expedition.dest;data.teeth+=100+idx*50;let rewardPool=["corail","coquillage","algue","poissons","amphore","meduse"];let reward=rewardPool[Math.min(rewardPool.length-1,idx)];data.inventory[reward]=(data.inventory[reward]||0)+1;data.completedExpeditions++;data.expedition=null;save();render();alert(`Expédition terminée ! +${100+idx*50} 🦷 et une décoration trouvée.`)}
function openGoal(id=""){let f=$("#goalForm");f.reset();f.elements.id.value=id;f.elements.start.value=today();$("#goalDialogTitle").textContent=id?"Modifier l'objectif":"Nouvel objectif";if(id){let g=data.goals.find(x=>x.id===id);Object.keys(g).forEach(k=>{if(f.elements[k]){if(f.elements[k].type==="checkbox")f.elements[k].checked=!!g[k];else f.elements[k].value=g[k]??""}})}$("#goalDialog").showModal()}
function openActivity(id){if(!data.goals.filter(g=>!g.archived).length)return alert("Crée d'abord un objectif.");let f=$("#activityForm");f.reset();populateActivity();f.elements.goal.value=id||data.goals.find(g=>!g.archived)?.id;f.elements.date.value=today();$("#activityDialog").showModal()}
function openAquarium(){renderAquarium();$("#aquariumScreen").classList.remove("hidden");$("#aquariumScreen").setAttribute("aria-hidden","false");document.body.classList.add("aquariumOpen");if(!data.oceanTutorialSeen){$("#aquariumHint").textContent="Bienvenue ! Ton kit de départ est déjà placé. Appuie sur « Décorer » pour personnaliser ton océan.";data.oceanTutorialSeen=true;save()}else $("#aquariumHint").textContent="Ton océan évolue avec ta progression."}
function closeAquarium(){selectedDecor=null;selectedPlaced=null;$("#aquariumScreen").classList.add("hidden");$("#aquariumScreen").classList.remove("editing");$("#aquariumEdit").classList.add("hidden");$("#aquariumScreen").setAttribute("aria-hidden","true");document.body.classList.remove("aquariumOpen");render()}
function setEditing(on){$("#aquariumScreen").classList.toggle("editing",on);$("#aquariumEdit").classList.toggle("hidden",!on);$("#editAquarium").textContent=on?"✏️ Édition":"✏️ Décorer";selectedDecor=null;selectedPlaced=null;renderAquarium();$("#aquariumHint").textContent=on?"Choisis un objet dans ton inventaire.":"Ton aquarium est sauvegardé."}
$("#aquariumCanvas").addEventListener("click",e=>{if(!$("#aquariumScreen").classList.contains("editing"))return;if(e.target.closest(".placedItem"))return;let r=$("#aquariumCanvas").getBoundingClientRect(),x=Math.max(3,Math.min(97,(e.clientX-r.left)/r.width*100)),y=Math.max(5,Math.min(94,(e.clientY-r.top)/r.height*100));placementHistory.push(JSON.stringify(data.placedDecor));if(selectedPlaced){let p=data.placedDecor.find(q=>q.id===selectedPlaced);if(p){p.x=x;p.y=y}}else if(selectedDecor&&availableCount(selectedDecor)>0){data.placedDecor.push({id:"p"+Date.now(),decor:selectedDecor,x,y})}save();selectedPlaced=null;renderAquarium();bindDynamic()});
$("#placedDecor").addEventListener("dblclick",e=>{let b=e.target.closest(".placedItem");if(!b||!$("#aquariumScreen").classList.contains("editing"))return;placementHistory.push(JSON.stringify(data.placedDecor));data.placedDecor=data.placedDecor.filter(p=>p.id!==b.dataset.pid);selectedPlaced=null;save();renderAquarium();bindDynamic();$("#aquariumHint").textContent="Objet rangé dans l'inventaire."});
$("#goalForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id=f.get("id"),obj={id:id||"g"+Date.now(),name:f.get("name"),category:f.get("category"),type:f.get("type"),target:+f.get("target"),unit:f.get("unit"),repeat:f.get("repeat"),start:f.get("start"),end:f.get("end"),baseline:+f.get("baseline")||0,flexible:!!f.get("flexible"),archived:false};if(id)Object.assign(data.goals.find(g=>g.id===id),obj);else data.goals.push(obj);save();$("#goalDialog").close();render()};
$("#activityForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),v=+f.get("value"),xp=Math.max(10,Math.min(100,Math.round(Math.abs(v)*10))),teeth=Math.max(3,Math.min(25,Math.round(Math.abs(v)*2)));data.activities.push({id:"a"+Date.now(),goal:f.get("goal"),value:v,date:f.get("date"),duration:+f.get("duration")||0,note:f.get("note"),rewardXP:xp,rewardTeeth:teeth});data.xp+=xp;data.teeth+=teeth;data.affinity[data.activeShark]=(data.affinity[data.activeShark]||0)+xp;if(data.expedition)data.expedition.progress+=xp;save();$("#activityDialog").close();render()};
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".page").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.page).classList.add("active");render()});
$("#newGoal").onclick=()=>openGoal();$("#quickAdd").onclick=()=>openActivity();$("#settingsBtn").onclick=()=>$("#settingsDialog").showModal();$("#closeSettings").onclick=()=>$("#settingsDialog").close();$("#prevWeek").onclick=()=>{weekOffset--;renderWeek()};$("#nextWeek").onclick=()=>{weekOffset++;renderWeek()};
$$(".goalFilter").forEach(c=>c.onclick=()=>{$$(".goalFilter").forEach(x=>x.classList.remove("active"));c.classList.add("active");goalFilter=c.dataset.filter;render()});
$$(".dexFilter").forEach(c=>c.onclick=()=>{$$(".dexFilter").forEach(x=>x.classList.remove("active"));c.classList.add("active");rarityFilter=c.dataset.rarity;renderDex();bindDynamic()});
$$(".decorFilter").forEach(c=>c.onclick=()=>{$$(".decorFilter").forEach(x=>x.classList.remove("active"));c.classList.add("active");decorFilter=c.dataset.kind;renderDecorShop();bindDynamic()});
const oceanLauncher=$("#openAquarium");let lastOceanOpen=0;function safeOpenAquarium(e){if(e){e.preventDefault();e.stopPropagation()}let now=Date.now();if(now-lastOceanOpen<350)return;lastOceanOpen=now;openAquarium()}
if(oceanLauncher){oceanLauncher.addEventListener("click",safeOpenAquarium);oceanLauncher.addEventListener("pointerup",e=>{if(e.pointerType==="touch")safeOpenAquarium(e)},{passive:false});oceanLauncher.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")safeOpenAquarium(e)})}
$("#closeAquarium").addEventListener("click",closeAquarium);$("#editAquarium").addEventListener("click",()=>setEditing(!$("#aquariumScreen").classList.contains("editing")));$("#doneDecor").addEventListener("click",()=>setEditing(false));$("#clearSelection").addEventListener("click",()=>{selectedDecor=null;selectedPlaced=null;renderAquarium();bindDynamic()});$("#undoDecor").addEventListener("click",()=>{if(!placementHistory.length)return;data.placedDecor=JSON.parse(placementHistory.pop());save();renderAquarium();bindDynamic()});
$("#analysisSelect").onchange=e=>{let g=data.goals.find(x=>x.id===e.target.value);if(!g)return;let a=actsFor(g).sort((x,y)=>x.date.localeCompare(y.date)),r=g.type==="metric"?[g.baseline||0,...a.map(x=>x.value)]:a.map((x,i)=>a.slice(0,i+1).reduce((s,y)=>s+y.value,0));if(!r.length)r=[0];let t=r.map((_,i)=>g.type==="metric"?(g.baseline||0)+(g.target-(g.baseline||0))*i/Math.max(1,r.length-1):g.target*i/Math.max(1,r.length-1));draw($("#analysisChart"),r,t);$("#analysisInsight").textContent=`${g.name} : ${+valueFor(g).toFixed(1)} ${g.unit||""} pour une cible de ${g.target} ${g.unit||""}.`};
$("#exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`sharkhabits-v4-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#importFile").onchange=async e=>{try{let d=JSON.parse(await e.target.files[0].text());if(!d.goals||!d.activities)throw 0;data=d;normalize();save();$("#settingsDialog").close();render();alert("Sauvegarde restaurée.")}catch{alert("Fichier de sauvegarde invalide.")}};
$("#resetBtn").onclick=()=>{if(confirm("Tout effacer ? Cette action est irréversible sauf si tu as exporté une sauvegarde.")){data=blank();save();$("#settingsDialog").close();render()}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{});render();