"use strict";
const SHARKS=[{"id":"grey","name":"Requin gris","rarity":"Commun","cost":0,"unlock":"Départ","img":"shark-grey.png"},{"id":"blacktip","name":"Requin pointe noire","rarity":"Commun","cost":350,"unlock":"Boutique","img":"shark-blacktip.png"},{"id":"whitetip","name":"Requin pointe blanche","rarity":"Commun","cost":450,"unlock":"Boutique","img":"shark-whitetip.png"},{"id":"blue","name":"Requin bleu","rarity":"Commun","cost":600,"unlock":"Boutique","img":"shark-blue.png"},{"id":"nurse","name":"Requin nourrice","rarity":"Commun","cost":700,"unlock":"Boutique","img":"shark-nurse.png"},{"id":"lemon","name":"Requin citron","rarity":"Commun","cost":800,"unlock":"Boutique","img":"shark-lemon.png"},{"id":"reef","name":"Requin corail","rarity":"Commun","cost":900,"unlock":"Boutique","img":"shark-reef.png"},{"id":"zebra","name":"Requin zèbre","rarity":"Rare","cost":1400,"unlock":"10 activités","img":"shark-zebra.png"},{"id":"thresher","name":"Requin-renard","rarity":"Rare","cost":1800,"unlock":"25 activités","img":"shark-thresher.png"},{"id":"mako","name":"Requin mako","rarity":"Rare","cost":2200,"unlock":"Niveau 10","img":"shark-mako.png"},{"id":"bull","name":"Requin bouledogue","rarity":"Rare","cost":2600,"unlock":"Boutique","img":"shark-bull.png"},{"id":"hammer","name":"Requin marteau","rarity":"Rare","cost":3000,"unlock":"10 objectifs atteints","img":"shark-hammer.png"},{"id":"wobbegong","name":"Requin-tapis","rarity":"Rare","cost":3200,"unlock":"Boutique","img":"shark-wobbegong.png"},{"id":"saw","name":"Requin-scie","rarity":"Rare","cost":3400,"unlock":"Boutique","img":"shark-saw.png"},{"id":"goblin","name":"Requin-lutin","rarity":"Épique","cost":5000,"unlock":"50 activités","img":"shark-goblin.png"},{"id":"frilled","name":"Requin-lézard","rarity":"Épique","cost":5500,"unlock":"Boutique","img":"shark-frilled.png"},{"id":"tiger","name":"Requin tigre","rarity":"Épique","cost":6000,"unlock":"Niveau 20","img":"shark-tiger.png"},{"id":"greenland","name":"Requin du Groenland","rarity":"Épique","cost":6500,"unlock":"100 activités","img":"shark-greenland.png"},{"id":"sixgill","name":"Requin griset","rarity":"Épique","cost":7000,"unlock":"Boutique","img":"shark-sixgill.png"},{"id":"angel","name":"Requin ange","rarity":"Épique","cost":7200,"unlock":"Boutique","img":"shark-angel.png"},{"id":"great-hammer","name":"Grand marteau","rarity":"Légendaire","cost":10000,"unlock":"Niveau 30","img":"shark-great-hammer.png"},{"id":"great-white","name":"Grand requin blanc","rarity":"Légendaire","cost":12000,"unlock":"Niveau 40","img":"shark-great-white.png"},{"id":"basking","name":"Requin pèlerin","rarity":"Légendaire","cost":14000,"unlock":"200 activités","img":"shark-basking.png"},{"id":"whale","name":"Requin-baleine","rarity":"Légendaire","cost":16000,"unlock":"Niveau 50","img":"shark-whale.png"},{"id":"megalodon","name":"Mégalodon","rarity":"Mythique","cost":25000,"unlock":"Collection ultime","img":"shark-megalodon.png"}];
const DECORS=[{"id":"seaweed","name":"Petite algue","kind":"plante","rarity":"Commun","cost":30,"img":"decor-seaweed.png"},{"id":"kelp","name":"Grande algue","kind":"plante","rarity":"Commun","cost":80,"img":"decor-kelp.png"},{"id":"coral-red","name":"Corail rouge","kind":"corail","rarity":"Commun","cost":120,"img":"decor-coral-red.png"},{"id":"anemone","name":"Anémone","kind":"corail","rarity":"Rare","cost":150,"img":"decor-anemone.png"},{"id":"rock","name":"Rocher volcanique","kind":"rocher","rarity":"Rare","cost":200,"img":"decor-rock.png"},{"id":"shell","name":"Coquillage","kind":"special","rarity":"Commun","cost":40,"img":"decor-shell.png"},{"id":"bluefish","name":"Poisson bleu","kind":"animal","rarity":"Commun","cost":100,"img":"decor-bluefish.svg"},{"id":"clownfish","name":"Poisson-clown","kind":"animal","rarity":"Rare","cost":180,"img":"decor-clownfish.svg"},{"id":"school","name":"Banc de poissons","kind":"animal","rarity":"Rare","cost":260,"img":"decor-school.svg"},{"id":"babyturtle","name":"Bébé tortue","kind":"animal","rarity":"Épique","cost":500,"img":"decor-babyturtle.svg"},{"id":"turtle","name":"Tortue marine","kind":"animal","rarity":"Épique","cost":800,"img":"decor-turtle.svg"},{"id":"wreck","name":"Épave ancienne","kind":"special","rarity":"Épique","cost":800,"img":"decor-wreck.png"},{"id":"statue","name":"Statue engloutie","kind":"special","rarity":"Épique","cost":1200,"img":"decor-statue.png"},{"id":"chest","name":"Coffre au trésor","kind":"special","rarity":"Légendaire","cost":1500,"img":"decor-chest.png"},{"id":"jelly","name":"Méduse lumineuse","kind":"animal","rarity":"Épique","cost":900,"img":"decor-jelly.png"}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DAY=86400000, EM={sport:"🏃",maison:"🧹",sante:"❤️",perso:"🌱"};
const iso=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}, today=()=>iso(new Date());
const blank=()=>({version:"14.0",xp:0,teeth:100,goals:[],activities:[],ownedSharks:["grey"],activeShark:"grey",aquariumSharks:["grey"],inventory:{seaweed:3,kelp:1,"coral-red":2,rock:2,shell:2},placed:[{id:"p1",decor:"seaweed",x:14,y:82},{id:"p2",decor:"rock",x:38,y:88},{id:"p3",decor:"coral-red",x:72,y:83},{id:"p4",decor:"shell",x:87,y:91}]});
const KEYS=["sharkHabitsV14","sharkHabitsV132","sharkHabitsV131","sharkHabitsV13","sharkHabitsV121","sharkHabitsV12","sharkHabitsV11","sharkHabitsV10","sharkHabitsV91","sharkHabitsV9","sharkHabitsV811","sharkHabitsV81","sharkHabitsV8","sharkHabitsV7","sharkHabitsV6","sharkHabitsV5"];
let loaded=null; for(const k of KEYS){try{loaded=JSON.parse(localStorage.getItem(k)||"null")}catch(e){} if(loaded)break}
let data=Object.assign(blank(),loaded||{},{version:"14.0"}); data.inventory=Object.assign(blank().inventory,data.inventory||{}); data.placed=Array.isArray(data.placed)?data.placed:[]; data.aquariumSharks=Array.isArray(data.aquariumSharks)?data.aquariumSharks:[data.activeShark||"grey"];
let selectedDate=today(),trackTab="today",rar="all",shopMode="decor",selectedDecor=null,selectedPlaced=null,history=[];
function save(){localStorage.setItem("sharkHabitsV14",JSON.stringify(data))}
function level(){return Math.floor(data.xp/250)+1} function monday(d=new Date()){d=new Date(d);let n=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-n);return d}
function bounds(g,d=new Date()){d=new Date(d);let s,e;if(g.repeat==="day"){s=new Date(d);s.setHours(0,0,0,0);e=new Date(s.getTime()+DAY)}else if(g.repeat==="month"){s=new Date(d.getFullYear(),d.getMonth(),1);e=new Date(d.getFullYear(),d.getMonth()+1,1)}else{s=monday(d);e=new Date(s.getTime()+7*DAY)}return[s,e]}
function acts(g){return data.activities.filter(a=>a.goal===g.id)}
function val(g,d=new Date()){let a=acts(g).slice().sort((x,y)=>x.date.localeCompare(y.date));if(g.type==="metric"){let q=a.filter(x=>x.date<=iso(d));return q.length?+q[q.length-1].value:+(g.baseline||0)}if(["long","once"].includes(g.type))return a.reduce((s,x)=>s+(+x.value||0),0);let [s,e]=bounds(g,d);return a.filter(x=>{let q=new Date(x.date+"T12:00");return q>=s&&q<e}).reduce((s,x)=>s+(+x.value||0),0)}
function pct(g,v=val(g)){if(g.type==="metric"){let b=+(g.baseline||0),t=+g.target;if(b===t)return 100;let progress=(v-b)/(t-b);return Math.max(0,Math.min(100,progress*100))}return Math.max(0,Math.min(100,g.target?v/g.target*100:0))}
function dailyVal(g,date=selectedDate){return acts(g).filter(a=>a.date===date).reduce((s,a)=>s+(+a.value||0),0)}
function scheduledFor(g,date){let days=Array.isArray(g.weekdays)?g.weekdays.map(Number):[];return !days.length||days.includes(new Date(date+"T12:00").getDay())}
function maxSharks(){return Math.min(5,1+Math.floor(level()/5))} function used(id){return data.placed.filter(p=>p.decor===id).length} function available(id){return Math.max(0,(data.inventory[id]||0)-used(id))}
function empty(t,i="🌊"){return `<div class="card empty"><div class="emptyIcon">${i}</div><b>${t}</b></div>`}
function calcStreak(){let set=new Set(data.activities.filter(a=>+a.value>0).map(a=>a.date)),n=0,d=new Date();while(set.has(iso(d))){n++;d=new Date(d.getTime()-DAY)}return n}
function v7AquariumMood(){let h=new Date().getHours(),bg=h>=7&&h<18?"linear-gradient(180deg,#1599b1 0%,#08748a 42%,#06374b 100%)":h>=18&&h<21?"linear-gradient(180deg,#e18b68 0%,#287a91 30%,#073a4d 68%,#041d2a 100%)":"linear-gradient(180deg,#082c48 0%,#06344a 45%,#031b29 100%)";document.documentElement.style.setProperty("--aquarium-bg",bg)}
function sprite(s,i){return `<img class="sharkSprite" src="${s.img}" alt="${s.name}" style="left:${8+(i*22)%65}%;top:${18+(i%3)*22}%;animation-delay:-${i*2}s">`}
function decorSprite(p,placed=false){let d=DECORS.find(x=>x.id===p.decor);return d?`<img class="decorSprite ${placed?"placed":""}" data-pid="${p.id}" src="${d.img}" alt="${d.name}" style="left:${p.x}%;top:${p.y}%">`:""}
function renderOcean(){let ss=data.aquariumSharks.filter(id=>data.ownedSharks.includes(id)).slice(0,maxSharks()).map(id=>SHARKS.find(s=>s.id===id)).filter(Boolean);$("#homeSharks").innerHTML=ss.map(sprite).join("");$("#homeDecor").innerHTML=data.placed.slice(0,12).map(p=>decorSprite(p)).join("");$("#aqSharks").innerHTML=ss.map(sprite).join("");$("#aqDecor").innerHTML=data.placed.map(p=>decorSprite(p,true)).join("");$("#aqLevel").textContent=`Niveau ${level()} · ${ss.length}/${maxSharks()} requins`;renderInventory()}
function goalCard(g,d=new Date(selectedDate+"T12:00")){let v=val(g,d),p=pct(g,v),dv=g.type==="metric"?val(g,d):Math.max(0,dailyVal(g,iso(d)));let period=g.repeat==="week"?"Cette semaine":g.repeat==="month"?"Ce mois":g.repeat==="day"?"Ce jour":"Progression";let dayText=g.type==="metric"?`Dernière mesure : ${v} ${g.unit||""}`:g.type==="habit"?`${dv} occurrence${dv>1?"s":""} ce jour`:`${+dv.toFixed(2)} ${g.unit||""} ce jour`;return `<div class="goalcard"><div class="goalTop"><span class="goalIcon">${EM[g.category]||"✓"}</span><div class="goalName">${g.name}<div class="muted">${dayText}</div></div><div class="stepper">${g.type==="metric"?"":`<button class="minus stepBtn" data-id="${g.id}">−</button>`}<button class="plus stepBtn" data-id="${g.id}">${g.type==="metric"?"✎":"＋"}</button></div></div><div class="progressrow"><span>${period} : ${+v.toFixed(2)} ${g.unit||""} / ${g.target} ${g.unit||""}</span><b>${Math.round(p)}%</b></div><div class="progress"><i style="width:${p}%"></i></div><div class="actions"><button class="textbtn edit" data-id="${g.id}">Modifier</button><button class="textbtn archive" data-id="${g.id}">${g.archived?"Réactiver":"Archiver"}</button><button class="danger del" data-id="${g.id}">Supprimer</button></div></div>`}
function renderWeekNavigator(){let host=$("#weekNavigator"),s=monday(new Date(selectedDate+"T12:00")),days=Array.from({length:7},(_,i)=>new Date(s.getTime()+i*DAY));host.innerHTML=`<button class="weekArrow prevWeek">‹</button>${days.map(x=>{let id=iso(x);return `<button class="dayPick ${id===selectedDate?"selected":""} ${id===today()?"isToday":""}" data-date="${id}"><span>${x.toLocaleDateString("fr-FR",{weekday:"short"}).replace(".","")}</span><b>${x.getDate()}</b></button>`}).join("")}<button class="weekArrow nextWeek">›</button>`}
function renderTracking(){renderWeekNavigator();let active=data.goals.filter(g=>!g.archived),shown=trackTab==="all"?active:active.filter(g=>scheduledFor(g,selectedDate));$("#trackingContent").innerHTML=shown.map(g=>goalCard(g,new Date(selectedDate+"T12:00"))).join("")||empty("Rien de prévu ce jour","☀️");$("#archived").innerHTML=data.goals.filter(g=>g.archived).map(g=>goalCard(g,new Date(selectedDate+"T12:00"))).join("")||'<p class="muted">Aucun suivi archivé.</p>'}
function draw(c,A,B=[]){if(!c)return;let x=c.getContext("2d"),w=c.width,h=c.height,p=35;x.clearRect(0,0,w,h);let vs=[...A,...B].filter(Number.isFinite);if(!vs.length)return;let mn=Math.min(...vs),mx=Math.max(...vs);if(mn===mx){mn--;mx++};let pt=(v,i,n)=>[p+i*(w-2*p)/Math.max(1,n-1),h-p-(v-mn)*(h-2*p)/(mx-mn)];x.strokeStyle="#dce7e9";for(let i=0;i<5;i++){let y=p+i*(h-2*p)/4;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()};[B,A].forEach((ar,j)=>{if(!ar.length)return;x.strokeStyle=j?"#076986":"#98a7aa";x.lineWidth=j?4:2;x.setLineDash(j?[]:[8,6]);x.beginPath();ar.forEach((v,i)=>{let [xx,y]=pt(v,i,ar.length);i?x.lineTo(xx,y):x.moveTo(xx,y)});x.stroke()});x.setLineDash([])}
function trajectory(g){let start=g.start?new Date(g.start+"T12:00"):null,end=g.end?new Date(g.end+"T12:00"):null;if(!start||!end||end<=start)return null;let now=new Date(),ratio=Math.max(0,Math.min(1,(now-start)/(end-start))),b=g.type==="metric"?+(g.baseline||0):0;return b+(+g.target-b)*ratio}
function renderStats(){let ws=[];for(let k=7;k>=0;k--){let d=new Date(Date.now()-k*7*DAY),g=data.goals.filter(x=>!x.archived&&x.repeat==="week");ws.push(g.length?g.reduce((s,x)=>s+pct(x,val(x,d)),0)/g.length:0)}draw($("#weekly"),ws,[100,100,100,100,100,100,100,100]);$("#summary").innerHTML=`<div class="stat"><span class="muted">🔥 Série</span><b>${calcStreak()} j</b></div><div class="stat"><span class="muted">Activités</span><b>${data.activities.length}</b></div><div class="stat"><span class="muted">🦷 Dents</span><b>${data.teeth}</b></div><div class="stat"><span class="muted">🦈 Requins</span><b>${data.ownedSharks.length}</b></div>`;let gs=data.goals.filter(g=>!g.archived);$("#analysis").innerHTML=gs.map(g=>`<option value="${g.id}">${g.name}</option>`).join("");renderAnalysis(gs.find(g=>g.id===$("#analysis").value)||gs[0])}
function renderAnalysis(g){if(!g){draw($("#goalChart"),[]);$("#insight").textContent="Crée un suivi pour voir sa trajectoire.";return}let a=acts(g).slice().sort((x,y)=>x.date.localeCompare(y.date)),r;if(g.type==="metric")r=[+(g.baseline||0),...a.map(x=>+x.value)];else{let sum=0;r=[0,...a.map(x=>sum+=+x.value||0)]}let ideal=trajectory(g),t=r.map((_,i)=>{let ratio=i/Math.max(1,r.length-1),b=g.type==="metric"?+(g.baseline||0):0;return b+(+g.target-b)*ratio});draw($("#goalChart"),r,t);let text=`Réel : ${+val(g).toFixed(1)} ${g.unit||""} · Cible : ${g.target} ${g.unit||""}.`;if(ideal!==null)text+=` Trajectoire attendue aujourd’hui : ${+ideal.toFixed(1)} ${g.unit||""}.`;$("#insight").textContent=text}
function sharkCard(s){let own=data.ownedSharks.includes(s.id);return `<div class="item"><img src="${s.img}" alt="${s.name}">${own?"":'<span class="lock">🔒</span>'}<div class="rarity">${s.rarity}</div><h3>${s.name}</h3><p>${own?"Possédé":`${s.cost} 🦷`}</p>${own?`<button class="primary small choose" data-id="${s.id}">${data.activeShark===s.id?"Actif":"Choisir"}</button>`:`<button class="primary small buyShark" data-id="${s.id}">Acheter · ${s.cost} 🦷</button>`}<button class="textbtn sharkInfo" data-id="${s.id}">Voir la fiche</button></div>`}
function renderSharks(){$("#dex").textContent=`${data.ownedSharks.length} / ${SHARKS.length}`;$("#sharkGrid").innerHTML=SHARKS.filter(s=>rar==="all"||s.rarity===rar).map(sharkCard).join("")}
function renderShop(){$("#shopGrid").innerHTML=shopMode==="shark"?SHARKS.map(sharkCard).join(""):DECORS.map(d=>`<div class="item"><img src="${d.img}" alt="${d.name}"><div class="rarity">${d.rarity}</div><h3>${d.name}</h3><span class="owned">Possédé : ${data.inventory[d.id]||0}</span><p><b>${d.cost} 🦷</b></p><button class="primary small buyDecor" data-id="${d.id}">Acheter</button></div>`).join("")}
function renderInventory(){$("#inventory").innerHTML=DECORS.filter(d=>(data.inventory[d.id]||0)>0).map(d=>`<button class="inv ${selectedDecor===d.id?"selected":""}" data-id="${d.id}" ${available(d.id)<=0?"disabled":""}><img src="${d.img}"><small>${d.name}</small><b>${available(d.id)} dispo.</b></button>`).join("")}
function renderManage(){$("#maxSharks").textContent=maxSharks();$("#manageGrid").innerHTML=SHARKS.filter(s=>data.ownedSharks.includes(s.id)).map(s=>`<label class="item manageCheck"><input type="checkbox" data-id="${s.id}" ${data.aquariumSharks.includes(s.id)?"checked":""}><img src="${s.img}"><b>${s.name}</b></label>`).join("")}
function render(){save();$("#teeth").textContent=data.teeth;$("#shopTeeth").textContent=data.teeth;renderOcean();let active=data.goals.filter(g=>!g.archived),tod=active.filter(g=>scheduledFor(g,today()));$("#todayList").innerHTML=tod.map(g=>goalCard(g,new Date(today()+"T12:00"))).join("")||empty("Rien à suivre aujourd'hui","☀️");$("#todayDone").textContent=`${tod.filter(g=>pct(g,val(g,new Date()))>=100).length} / ${tod.length}`;$("#streak").textContent=`${calcStreak()} jour${calcStreak()>1?"s":""}`;renderTracking();renderStats();renderSharks();renderShop()}
function addActivity(g,value,date=selectedDate,note=""){value=+value;if(!Number.isFinite(value))return;if(g.type!=="metric"&&value<0){let available=Math.max(0,dailyVal(g,date));value=-Math.min(Math.abs(value),available);if(!value)return}data.activities.push({id:"a"+Date.now()+Math.random().toString(36).slice(2,6),goal:g.id,value,date,note,xp:value>0?10:0});if(value>0){data.xp+=10;data.teeth+=3}save();render()}
function adjustGoal(id,sign){let g=data.goals.find(x=>x.id===id);if(!g)return;if(g.type==="metric"){let raw=prompt(`Nouvelle mesure (${g.unit||"unité"}) :`,String(val(g,new Date(selectedDate+"T12:00"))||""));if(raw===null)return;let n=parseFloat(raw.replace(",","."));if(Number.isFinite(n))addActivity(g,n,selectedDate);return}if(g.type==="habit")return addActivity(g,sign>0?1:-1,selectedDate);let raw=prompt(`${sign>0?"Ajouter":"Retirer"} aujourd’hui (${g.unit||"unité"}) :`,"");if(raw===null)return;let n=parseFloat(raw.replace(",","."));if(Number.isFinite(n)&&n>0)addActivity(g,sign*n,selectedDate)}
function openGoal(id=""){let f=$("#goalForm");f.reset();f.elements.id.value=id;f.elements.start.value=today();let g=id?data.goals.find(x=>x.id===id):null;if(g){["name","category","type","target","unit","repeat","start","end","baseline"].forEach(k=>{if(f.elements[k])f.elements[k].value=g[k]??""})}$$('#goalForm input[name="weekdays"]').forEach(c=>c.checked=!!(g&&Array.isArray(g.weekdays)&&g.weekdays.map(Number).includes(+c.value)));$("#goalDialog").showModal()}
function openActivity(){let gs=data.goals.filter(g=>!g.archived);if(!gs.length)return openGoal();$("#activityGoal").innerHTML=gs.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");let f=$("#activityForm");f.reset();f.elements.date.value=selectedDate;$("#activityDialog").showModal()}
function openSharkDetail(id){let s=SHARKS.find(x=>x.id===id);if(!s)return;let own=data.ownedSharks.includes(id);$("#detailImg").src=s.img;$("#detailImg").alt=s.name;$("#detailName").textContent=s.name;$("#detailLatin").textContent="SharkHabits Collection";$("#detailRarity").textContent=s.rarity;$("#detailSize").textContent="—";$("#detailHabitat").textContent="Océan";$("#detailFact").textContent="Une espèce de la collection SharkHabits.";$("#detailUnlock").textContent=own?"Possédé":`${s.cost} dents`;$("#detailLock").textContent=own?"":"🔒";let a=$("#detailAction");a.textContent=own?(data.activeShark===id?"Requin actif":"Choisir ce requin"):`Acheter · ${s.cost} 🦷`;a.onclick=()=>{if(own){data.activeShark=id;if(!data.aquariumSharks.includes(id))data.aquariumSharks[0]=id}else{if(data.teeth<s.cost)return alert("Pas assez de dents.");data.teeth-=s.cost;data.ownedSharks.push(id)}save();render();$("#sharkDetail").close()};$("#sharkDetail").showModal()}
function openAquarium(){renderOcean();$("#aquarium").classList.remove("hidden");document.body.style.overflow="hidden";$("#aqTip").textContent="Touchez Décorer pour personnaliser votre océan."}
function closeAquarium(){$("#aquarium").classList.add("hidden");$("#editor").classList.add("hidden");selectedDecor=selectedPlaced=null;document.body.style.overflow=""}
function toggleEdit(on){$("#editor").classList.toggle("hidden",!on);$("#aqCanvas").classList.toggle("editing",on);selectedDecor=selectedPlaced=null;history=[];renderInventory();$("#aqTip").textContent=on?"Choisissez un élément puis touchez l’aquarium pour le placer. Touchez un élément placé pour le supprimer.":""}
function placeAt(e){if($("#editor").classList.contains("hidden"))return;let placed=e.target.closest(".placed");if(placed){let pid=placed.dataset.pid;history.push(JSON.stringify(data.placed));data.placed=data.placed.filter(p=>p.id!==pid);save();renderOcean();return}if(!selectedDecor||available(selectedDecor)<=0)return;let r=$("#aqCanvas").getBoundingClientRect(),x=Math.max(3,Math.min(97,(e.clientX-r.left)/r.width*100)),y=Math.max(5,Math.min(95,(e.clientY-r.top)/r.height*100));history.push(JSON.stringify(data.placed));data.placed.push({id:"p"+Date.now(),decor:selectedDecor,x:+x.toFixed(1),y:+y.toFixed(1)});save();renderOcean()}
function installStaticEvents(){
 document.querySelector('nav').addEventListener('click',e=>{let b=e.target.closest('button[data-page]');if(!b)return;$$('main>.page').forEach(s=>s.classList.toggle('active',s.id===b.dataset.page));$$('nav button').forEach(x=>x.classList.toggle('active',x===b));let names={home:'Mon océan',tracking:'Mon suivi',stats:'Mes statistiques',sharks:'Sharkdex',shop:'Boutique'};$("#title").textContent=names[b.dataset.page]||'SharkHabits';window.scrollTo(0,0)});
 $("#oceanCard").addEventListener('click',openAquarium);$("#aqBack").addEventListener('click',closeAquarium);$("#aqEdit").addEventListener('click',()=>toggleEdit(true));$("#doneEdit").addEventListener('click',()=>toggleEdit(false));$("#aqCanvas").addEventListener('click',placeAt);
 $("#aqManage").addEventListener('click',()=>{renderManage();$("#manageDialog").showModal()});$(".closeManage").addEventListener('click',()=>$("#manageDialog").close());$("#manageDone").addEventListener('click',()=>{let ids=$$('#manageGrid input:checked').map(x=>x.dataset.id).slice(0,maxSharks());if(!ids.length)ids=[data.activeShark];data.aquariumSharks=ids;save();$("#manageDialog").close();renderOcean()});
 $("#undo").addEventListener('click',()=>{if(!history.length)return;data.placed=JSON.parse(history.pop());save();renderOcean()});
 $("#quickAdd").addEventListener('click',openActivity);$("#newGoal").addEventListener('click',()=>openGoal());$("#settings").addEventListener('click',()=>$("#settingsDialog").showModal());
 $(".closeGoal").addEventListener('click',()=>$("#goalDialog").close());$(".closeActivity").addEventListener('click',()=>$("#activityDialog").close());$(".closeSettings").addEventListener('click',()=>$("#settingsDialog").close());$(".closeDetail").addEventListener('click',()=>$("#sharkDetail").close());
 $$('.trackTab').forEach(b=>b.addEventListener('click',()=>{trackTab=b.dataset.tab;$$('.trackTab').forEach(x=>x.classList.toggle('active',x===b));renderTracking()}));
 $$('.sharkFilter').forEach(b=>b.addEventListener('click',()=>{rar=b.dataset.r;$$('.sharkFilter').forEach(x=>x.classList.toggle('active',x===b));renderSharks()}));
 $$('.shopMode').forEach(b=>b.addEventListener('click',()=>{shopMode=b.dataset.mode;$$('.shopMode').forEach(x=>x.classList.toggle('active',x===b));renderShop()}));
 $("#analysis").addEventListener('change',()=>renderAnalysis(data.goals.find(g=>g.id===$("#analysis").value)));
 $("#goalForm").addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),id=f.get('id'),o={id:id||'g'+Date.now(),name:f.get('name'),category:f.get('category'),type:f.get('type'),target:+f.get('target'),unit:f.get('unit'),repeat:f.get('repeat'),start:f.get('start'),end:f.get('end'),baseline:+f.get('baseline')||0,weekdays:f.getAll('weekdays').map(Number),archived:false};if(id)Object.assign(data.goals.find(g=>g.id===id),o);else data.goals.push(o);save();$("#goalDialog").close();render()});
 $("#activityForm").addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target),g=data.goals.find(x=>x.id===f.get('goal'));if(g){let n=parseFloat(String(f.get('value')).replace(',','.'));if(Number.isFinite(n))addActivity(g,n,f.get('date'),f.get('note'))}$("#activityDialog").close()});
 $("#export").addEventListener('click',()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='sharkhabits-v14-backup.json';a.click();URL.revokeObjectURL(a.href)});
 $("#import").addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{data=Object.assign(blank(),JSON.parse(r.result),{version:'14.0'});save();render();$("#settingsDialog").close()}catch(err){alert('Sauvegarde invalide.')}};r.readAsText(f)});
 $("#reset").addEventListener('click',()=>{if(confirm('Effacer toutes les données SharkHabits ?')){data=blank();save();render();$("#settingsDialog").close()}});
 document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;let id=b.dataset.id;if(b.classList.contains('plus'))adjustGoal(id,1);else if(b.classList.contains('minus'))adjustGoal(id,-1);else if(b.classList.contains('edit'))openGoal(id);else if(b.classList.contains('archive')){let g=data.goals.find(x=>x.id===id);if(g){g.archived=!g.archived;save();render()}}else if(b.classList.contains('del')){if(confirm('Supprimer ce suivi et ses activités ?')){data.goals=data.goals.filter(g=>g.id!==id);data.activities=data.activities.filter(a=>a.goal!==id);save();render()}}else if(b.classList.contains('dayPick')){selectedDate=b.dataset.date;renderTracking()}else if(b.classList.contains('prevWeek')||b.classList.contains('nextWeek')){let d=new Date(selectedDate+'T12:00');d.setDate(d.getDate()+(b.classList.contains('nextWeek')?7:-7));selectedDate=iso(d);renderTracking()}else if(b.classList.contains('choose')){data.activeShark=id;if(!data.aquariumSharks.includes(id))data.aquariumSharks[0]=id;save();render()}else if(b.classList.contains('buyShark')){let s=SHARKS.find(x=>x.id===id);if(data.teeth<s.cost)return alert('Pas assez de dents.');data.teeth-=s.cost;if(!data.ownedSharks.includes(id))data.ownedSharks.push(id);save();render()}else if(b.classList.contains('buyDecor')){let d=DECORS.find(x=>x.id===id);if(data.teeth<d.cost)return alert('Pas assez de dents.');data.teeth-=d.cost;data.inventory[id]=(data.inventory[id]||0)+1;save();render()}else if(b.classList.contains('inv')){selectedDecor=id;renderInventory()}else if(b.classList.contains('sharkInfo'))openSharkDetail(id)});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$("#aquarium").classList.contains('hidden'))closeAquarium();$$('dialog[open]').forEach(d=>d.close())}})
}
v7AquariumMood();installStaticEvents();try{render()}catch(err){console.error(err);alert('SharkHabits a rencontré une erreur de rendu. Recharge la page ou importe ta sauvegarde.') }
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(console.warn);
